import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'es': {
      // Navegación
      'nav_events': 'Eventos',
      'nav_mgmt': 'Gestión',
      'nav_results': 'Resultados',
      'nav_profile': 'Perfil',
      
      // Home / Calendario
      'cal_title': 'Calendario',
      'search_events': 'Buscar eventos...',
      'today': 'Hoy',
      'no_events': 'No hay carreras programadas',
      'future_events': 'Próximos Eventos',
      'events_of_day': 'Eventos del día',

      // Perfil
      'profile_title': 'Mi Perfil',
      'full_name': 'Nombre Completo',
      'email': 'Correo Electrónico',
      'role': 'Rol de Usuario',
      'transponders': 'Mis Transponders',
      'edit_profile': 'EDITAR PERFIL',
      'save': 'GUARDAR',
      'cancel': 'CANCELAR',
      'settings': 'Ajustes de la Aplicación',
      'language': 'Idioma',
      'theme': 'Tema Visual',
      'logout': 'Cerrar Sesión',
      
      // Transponders
      'ts_number': 'Número',
      'ts_name': 'Nombre',
      'ts_error': 'Debes introducir un número válido y un nombre',
      'ts_success': 'Perfil actualizado correctamente',

      // Login
      'login_email_label': 'CORREO ELECTRÒNICO',
      'login_password_label': 'CONTRASEÑA',
      'login_btn': 'INICIAR SESIÓN',
      'loading': 'CARGANDO...',
      'create_account_btn': 'CREAR CUENTA NUEVA',

      // Register
      'register_title': 'Registro',
      'register_name_label': 'NOMBRE Y APELLIDO',
      'register_confirm_password': 'CONFIRMAR CONTRASEÑA',
      'register_btn': 'CREAR CUENTA',
      'registering': 'REGISTRANDO...',
      'back_to_login': 'VOLVER AL LOGIN',
      'hint_name': 'Tu nombre completo',
      'hint_email': 'ejemplo@rcsync.com',
      'hint_password_confirm': 'Repite tu contraseña',

      // Resultados
      'res_title': 'Resultados',
      'res_championship': 'Campeonato',
      'res_year': 'Año',
      'res_category': 'Categoría',
      'res_level': 'Nivel',
      'res_active': '🏎️ CAMPEONATO EN CURSO (Suma total)',
      'res_finished': '🏆 FINALIZADO (Suma 4 mejores)',
      'res_select_filters': 'Selecciona los filtros superiores',
      'res_loading': 'Cargando...',

      // Admin Dashboard
      'adm_title': 'Panel de Gestión',
      'adm_tab_events': 'Eventos',
      'adm_tab_champs': 'Campeonatos',
      'adm_tab_regs': 'Inscripciones',
      'adm_no_events': 'No hay eventos activos',
      'adm_no_champs': 'No hay campeonatos activos para editar',
      'adm_no_regs': 'No hay inscripciones pendientes',
      'adm_confirm': 'Confirmar',
      'adm_success_title': 'Éxito',
      'adm_success_created': 'Creado correctamente',
      'adm_year': 'Año',

      // Crear/Editar Evento
      'evt_create_title': 'Crear Nuevo Evento',
      'evt_edit_title': 'Modificar Evento',
      'evt_name': 'Nombre del Evento',
      'evt_desc': 'Descripción',
      'evt_price': 'Precio de Inscripción (€)',
      'evt_img': 'Imagen del Evento',
      'evt_config': 'Configuración',
      'evt_circuit': 'Seleccionar Circuito',
      'evt_champ_opt': 'Seleccionar Campeonato (Opcional)',
      'evt_dates': 'Fechas del Evento',
      'evt_start': 'Fecha Inicio Evento',
      'evt_end': 'Fecha Fin Evento',
      'evt_reg_dates': 'Fechas de Inscripción',
      'evt_reg_start': 'Inicio Inscripciones',
      'evt_reg_end': 'Fin Inscripciones',
      'evt_save': 'GUARDAR CAMBIOS',
      'evt_create_btn': 'CREAR EVENTO',
      'evt_none': 'Ninguno / General',
      'evt_sel_date': 'Seleccionar fecha',
      'evt_touch_img': 'Toca para subir una imagen',

      // Formulario Campeonato
      'cha_new': 'NUEVO CAMPEONATO',
      'cha_edit': 'MODIFICAR CAMPEONATO',
      'cha_name': 'Nombre del Campeonato',
      'cha_year': 'Año',
      'cha_active': 'Activo',
      'cha_add_cat': 'Añadir Categoría',
      'cha_cat_hint': 'Ej. Tamiya GT',
      'cha_configured': 'CATEGORÍAS CONFIGURADAS',
      'cha_pdf_ready': '📄 PDF listo para subir',
      'cha_pdf_ok': '✅ Reglamento subido',
      'cha_pdf_no': '⚠️ Sin reglamento adjunto',
      'cha_btn_save': 'GUARDAR CAMBIOS',
      'cha_btn_create': 'CREAR CAMPEONATO',
      'required': 'Requerido',
    },
    'en': {
      'nav_events': 'Events',
      'nav_mgmt': 'Management',
      'nav_results': 'Results',
      'nav_profile': 'Profile',
      
      'cal_title': 'Calendar',
      'search_events': 'Search events...',
      'today': 'Today',
      'no_events': 'No scheduled races',
      'future_events': 'Future Events',
      'events_of_day': 'Events of the day',

      'profile_title': 'My Profile',
      'full_name': 'Full Name',
      'email': 'Email Address',
      'role': 'User Role',
      'transponders': 'My Transponders',
      'edit_profile': 'EDIT PROFILE',
      'save': 'SAVE',
      'cancel': 'CANCEL',
      'settings': 'App Settings',
      'language': 'Language',
      'theme': 'Visual Theme',
      'logout': 'Logout',

      'ts_number': 'Number',
      'ts_name': 'Name',
      'ts_error': 'You must enter a valid number and name',
      'ts_success': 'Profile updated successfully',

      // Login
      'login_email_label': 'EMAIL ADDRESS',
      'login_password_label': 'PASSWORD',
      'login_btn': 'LOG IN',
      'loading': 'LOADING...',
      'create_account_btn': 'CREATE NEW ACCOUNT',

      // Register
      'register_title': 'Register',
      'register_name_label': 'FULL NAME',
      'register_confirm_password': 'CONFIRM PASSWORD',
      'register_btn': 'CREATE ACCOUNT',
      'registering': 'REGISTERING...',
      'back_to_login': 'BACK TO LOGIN',
      'hint_name': 'Your full name',
      'hint_email': 'example@rcsync.com',
      'hint_password_confirm': 'Repeat your password',

      // Resultados
      'res_title': 'Results',
      'res_championship': 'Championship',
      'res_year': 'Year',
      'res_category': 'Category',
      'res_level': 'Level',
      'res_active': '🏎️ CHAMPIONSHIP IN PROGRESS (Gross sum)',
      'res_finished': '🏆 FINISHED (Sum of best 4)',
      'res_select_filters': 'Select the filters above',
      'res_loading': 'Loading...',

      // Admin Dashboard
      'adm_title': 'Management Panel',
      'adm_tab_events': 'Events',
      'adm_tab_champs': 'Championships',
      'adm_tab_regs': 'Registrations',
      'adm_no_events': 'No active events',
      'adm_no_champs': 'No active championships to edit',
      'adm_no_regs': 'No pending registrations',
      'adm_confirm': 'Confirm',
      'adm_success_title': 'Success',
      'adm_success_created': 'Created successfully',
      'adm_year': 'Year',

      // Crear/Editar Evento
      'evt_create_title': 'Create New Event',
      'evt_edit_title': 'Modify Event',
      'evt_name': 'Event Name',
      'evt_desc': 'Description',
      'evt_price': 'Entry Fee (€)',
      'evt_img': 'Event Image',
      'evt_config': 'Configuration',
      'evt_circuit': 'Select Circuit',
      'evt_champ_opt': 'Select Championship (Optional)',
      'evt_dates': 'Event Dates',
      'evt_start': 'Event Start Date',
      'evt_end': 'Event End Date',
      'evt_reg_dates': 'Registration Dates',
      'evt_reg_start': 'Registration Start',
      'evt_reg_end': 'Registration End',
      'evt_save': 'SAVE CHANGES',
      'evt_create_btn': 'CREATE EVENT',
      'evt_none': 'None / General',
      'evt_sel_date': 'Select date',
      'evt_touch_img': 'Tap to upload an image',

      // Formulario Campeonato
      'cha_new': 'NEW CHAMPIONSHIP',
      'cha_edit': 'MODIFY CHAMPIONSHIP',
      'cha_name': 'Championship Name',
      'cha_year': 'Year',
      'cha_active': 'Active',
      'cha_add_cat': 'Add Category',
      'cha_cat_hint': 'e.g. Tamiya GT',
      'cha_configured': 'CONFIGURED CATEGORIES',
      'cha_pdf_ready': '📄 PDF ready to upload',
      'cha_pdf_ok': '✅ Rulebook uploaded',
      'cha_pdf_no': '⚠️ No rulebook attached',
      'cha_btn_save': 'SAVE CHANGES',
      'cha_btn_create': 'CREATE CHAMPIONSHIP',
      'required': 'Required',
    },
    'ca': {
      'nav_events': 'Esdeveniments',
      'nav_mgmt': 'Gestió',
      'nav_results': 'Resultats',
      'nav_profile': 'Perfil',
      
      'cal_title': 'Calendari',
      'search_events': 'Cercar esdeveniments...',
      'today': 'Avui',
      'no_events': 'No hi ha curses programades',
      'future_events': 'Pròxims Esdeveniments',
      'events_of_day': 'Esdeveniments del dia',

      'profile_title': 'El meu Perfil',
      'full_name': 'Nom Complet',
      'email': 'Correu Electrònic',
      'role': 'Rol d\'Usuari',
      'transponders': 'Els meus Transponders',
      'edit_profile': 'EDITAR PERFIL',
      'save': 'GUARDAR',
      'cancel': 'CANCEL·LAR',
      'settings': 'Ajustos de l\'Aplicació',
      'language': 'Idioma',
      'theme': 'Tema Visual',
      'logout': 'Tancar Sessió',

      'ts_number': 'Número',
      'ts_name': 'Nom',
      'ts_error': 'Has d\'introduir un número vàlid i un nom',
      'ts_success': 'Perfil actualitzat correctament',

      // Login
      'login_email_label': 'CORREU ELECTRÒNIC',
      'login_password_label': 'CONTRASENYA',
      'login_btn': 'INICIAR SESSIÓ',
      'loading': 'CARREGANT...',
      'create_account_btn': 'CREAR COMPTE NOU',

      // Register
      'register_title': 'Registre',
      'register_name_label': 'NOM I COGNOMS',
      'register_confirm_password': 'CONFIRMAR CONTRASENYA',
      'register_btn': 'CREAR COMPTE',
      'registering': 'REGISTRANT...',
      'back_to_login': 'TORNAR AL LOGIN',
      'hint_name': 'El teu nom complet',
      'hint_email': 'exemple@rcsync.com',
      'hint_password_confirm': 'Repeteix la teva contrasenya',

      // Resultados
      'res_title': 'Resultats',
      'res_championship': 'Campionat',
      'res_year': 'Any',
      'res_category': 'Categoria',
      'res_level': 'Nivell',
      'res_active': '🏎️ CAMPIONAT EN CURS (Suma total)',
      'res_finished': '🏆 FINALITZAT (Suma 4 millors)',
      'res_select_filters': 'Selecciona els filtres superiors',
      'res_loading': 'Carregant...',

      // Admin Dashboard
      'adm_title': 'Panel de Gestió',
      'adm_tab_events': 'Esdeveniments',
      'adm_tab_champs': 'Campionats',
      'adm_tab_regs': 'Inscripcions',
      'adm_no_events': 'No hi ha esdeveniments actius',
      'adm_no_champs': 'No hi ha campionats actius per editar',
      'adm_no_regs': 'No hi ha inscripcions pendents',
      'adm_confirm': 'Confirmar',
      'adm_success_title': 'Èxit',
      'adm_success_created': 'Creat correctament',
      'adm_year': 'Any',

      // Crear/Editar Evento
      'evt_create_title': 'Crear Nou Esdeveniment',
      'evt_edit_title': 'Modificar Esdeveniment',
      'evt_name': 'Nom de l\'Esdeveniment',
      'evt_desc': 'Descripció',
      'evt_price': 'Preu d\'Inscripció (€)',
      'evt_img': 'Imatge de l\'Esdeveniment',
      'evt_config': 'Configuració',
      'evt_circuit': 'Seleccionar Circuit',
      'evt_champ_opt': 'Seleccionar Campionat (Opcional)',
      'evt_dates': 'Dates de l\'Esdeveniment',
      'evt_start': 'Data Inici Esdeveniment',
      'evt_end': 'Data Fi Esdeveniment',
      'evt_reg_dates': 'Dates d\'Inscripció',
      'evt_reg_start': 'Inici Inscripcions',
      'evt_reg_end': 'Fi Inscripcions',
      'evt_save': 'GUARDAR CANVIS',
      'evt_create_btn': 'CREAR ESDEVENIMENT',
      'evt_none': 'Cap / General',
      'evt_sel_date': 'Seleccionar data',
      'evt_touch_img': 'Toca per pujar una imatge',

      // Formulario Campeonato
      'cha_new': 'NOU CAMPIONAT',
      'cha_edit': 'MODIFICAR CAMPIONAT',
      'cha_name': 'Nom del Campionat',
      'cha_year': 'Any',
      'cha_active': 'Actiu',
      'cha_add_cat': 'Afegir Categoria',
      'cha_cat_hint': 'Ex. Tamiya GT',
      'cha_configured': 'CATEGORIES CONFIGURADES',
      'cha_pdf_ready': '📄 PDF llist per pujar',
      'cha_pdf_ok': '✅ Reglament pujat',
      'cha_pdf_no': '⚠️ Sense reglament adjunt',
      'cha_btn_save': 'GUARDAR CANVIS',
      'cha_btn_create': 'CREAR CAMPIONAT',
      'required': 'Requerit',
    },
  };
}
